### ISSUE TITLE
slash command is not working plz help

### ISSUE THREAD

**Issue by ShrimantaGarain** [eliangerard/discord-assistant-v2#1]

**Comment by eliangerard** [comment]
Can you give me more information? Are you unable to use Slash Command or are you not getting a response?

**Comment by ShrimantaGarain** [comment]
yes there is no response from the bot ...actually there is no / cmd option available to discord chat box. also there is no error with code running console and the permission is also 8

**Comment by D3FAU4T** [comment]
Hi, I fixed this issue by changing the last part a little bit, seems like you now need async and await to register the slash commands, something like this... so after the const rest line, delete that and put this and the commands should register >>
```javascript
(async () => {
  try {
    console.log('Started refreshing application (/) commands.');
    await rest.put(Routes.applicationCommands(clientId), { body: commands })
	.then(() => console.log('Successfully registered application commands.'))
	.catch(console.error);
  } catch (error) {
    console.error(error);
  }
})();
```

Pero @eliangerard hay un problema, el bot no habla en el canal de voz, solo responde en texto 😬, También tuve que poner esta línea en el archivo Response.js; de lo contrario, para algunas consultas, el bot envía un mensaje vacío y se atasca con la API de discord 😥 `if (text.length == 0 || text == "") return;`

**Comment by eliangerard** [comment]
Hola, 4 meses después ya está arreglado, agregué lo que me dijiste @D3FAU4T y por lo de los mensajes vacíos, aparentemente el API de Google Assistant no siempre devuelve una respuesta con texto, este actúa como ayuda visual pero no siempre tiene que existir, por la naturaleza del asistente, así que si eso sucede, lo indica, muchas gracias :)
